-- PostgreSQL schema for the future 26ai DB connection.
CREATE SCHEMA IF NOT EXISTS staffing;
CREATE TABLE staffing.people (person_id text PRIMARY KEY, full_name text NOT NULL, initials text NOT NULL, job_title text NOT NULL, location text, allocation_pct numeric(5,2) NOT NULL CHECK (allocation_pct BETWEEN 0 AND 100), active_pods integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE staffing.interests (interest_id bigserial PRIMARY KEY, interest_name text NOT NULL UNIQUE, category text);
CREATE TABLE staffing.person_interests (person_id text REFERENCES staffing.people(person_id) ON DELETE CASCADE, interest_id bigint REFERENCES staffing.interests(interest_id), strength smallint NOT NULL CHECK (strength BETWEEN 1 AND 5), evidence_note text, PRIMARY KEY(person_id, interest_id));
CREATE TABLE staffing.requests (request_id text PRIMARY KEY, title text NOT NULL, work_type text NOT NULL, owner_name text NOT NULL, needed_by date NOT NULL, estimated_hours numeric(8,2) NOT NULL, priority text NOT NULL CHECK (priority IN ('High','Normal','Urgent')), status text NOT NULL CHECK (status IN ('Needs recommendation','In review','Staffed','Draft')), business_context text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE staffing.request_requirements (request_id text REFERENCES staffing.requests(request_id) ON DELETE CASCADE, interest_id bigint REFERENCES staffing.interests(interest_id), required_strength smallint NOT NULL DEFAULT 3 CHECK (required_strength BETWEEN 1 AND 5), PRIMARY KEY(request_id,interest_id));
CREATE TABLE staffing.availability_events (event_id bigserial PRIMARY KEY, person_id text REFERENCES staffing.people(person_id) ON DELETE CASCADE, event_type text NOT NULL CHECK (event_type IN ('OOO','Leave','Travel','Training','Commitment')), starts_on date NOT NULL, ends_on date NOT NULL, title text NOT NULL, allocated_hours numeric(7,2), CHECK (ends_on >= starts_on));
CREATE TABLE staffing.recommendations (recommendation_id bigserial PRIMARY KEY, request_id text NOT NULL REFERENCES staffing.requests(request_id), person_id text NOT NULL REFERENCES staffing.people(person_id), role_in_pod text NOT NULL, score numeric(5,2) NOT NULL, rationale text, decision_status text NOT NULL DEFAULT 'Pending review' CHECK (decision_status IN ('Pending review','Approved','Adjusted','Declined')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(request_id,person_id));
CREATE TABLE staffing.chat_audit (chat_id bigserial PRIMARY KEY, actor_id text, prompt text NOT NULL, response_summary text, model_name text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_requests_status ON staffing.requests(status);
CREATE INDEX idx_availability_person_dates ON staffing.availability_events(person_id, starts_on, ends_on);
CREATE OR REPLACE VIEW staffing.v_staffing_snapshot AS SELECT p.person_id,p.full_name,p.job_title,p.location,p.allocation_pct,p.active_pods,coalesce(string_agg(i.interest_name || ':' || pi.strength, ', ' ORDER BY pi.strength DESC), '') AS interests FROM staffing.people p LEFT JOIN staffing.person_interests pi ON pi.person_id=p.person_id LEFT JOIN staffing.interests i ON i.interest_id=pi.interest_id GROUP BY p.person_id,p.full_name,p.job_title,p.location,p.allocation_pct,p.active_pods;
-- Excel load pattern: export each sheet as CSV and use \copy from psql.
-- \copy staffing.people(person_id,full_name,initials,job_title,location,allocation_pct,active_pods) FROM 'people.csv' CSV HEADER;
-- \copy staffing.requests(request_id,title,work_type,owner_name,needed_by,estimated_hours,priority,status,business_context) FROM 'requests.csv' CSV HEADER;
